networks:
  ddltower:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:dead:beef::/64

services:
  ddltower:
    image: dmachard/ddl-tower:latest
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - ${DOCKER_GID:-983}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:8000"
    networks:
      - ddltower
    environment:
      - NODE_NO_WARNINGS=1
      - TZ=Europe/Paris
    depends_on:
      - ddltower-browser
    restart: always

  ddltower-browser:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: ddltower-browser
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - TITLE=DDLtower Chromium
    # to avoid 127.0.0.1 resolution and IPv6 priority
    # extra_hosts:
    #   - "xxxxxx.com:[IP_ADDRESS]"
    volumes:
      - ./webtop_data:/config
    ports:
      - 8002:3000
    networks:
      - ddltower
    shm_size: "1gb"
    restart: unless-stopped
