networks:
  ddltower:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:dead:beef::/64

services:
  ddltower:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - ${DOCKER_GID:-983}
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:8000"
    environment:
      - NODE_NO_WARNINGS=1
    networks:
      - ddltower
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    depends_on:
      - ddltower-browser
    restart: always

  ddltower-browser:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: ddltower-browser
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
    cap_add:
      - SYS_ADMIN
    # to avoid 127.0.0.1 resolution and IPv6 priority
    extra_hosts:
      - "xxxxxx.com:[IP_ADDRESS]"
    user: root
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - SUBFOLDER=/ #optional
      - TITLE=DDLtower Chromium
    volumes:
      - ./webtop_data:/config
    networks:
      - ddltower
    ports:
      - 8002:3000
    shm_size: "1gb"
    restart: unless-stopped
