services:
  ddltower:
    image: dmachard/ddl-tower:latest
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - ${DOCKER_GID:-983}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:8001"
    restart: always

  ddltower-browser:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: ddltower-browser
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - TITLE=Webtop Chromium
    volumes:
      - ./webtop_data:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped
