services:
  ddltower:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./config:/app/config
    ports:
      - "8001:8001"
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload" ]
    restart: always
